app = "nullspire-backend"

[build]

[env]
PORT = "3001"

[[mounts]]
source = "data_volume"
destination = "/data"

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
